Align Integrations Documentation Structure
nautobot/nautobot-app-chatops pull request #265
Opened 2023-09-25 11:48 UTC by snaselj

# Closes: NaN

## What's Changed

- Aligned integrations documentation structure with SSoT.

2023-09-25 11:50 UTC, snaselj commented
@cmsirbu Could you pls. check this?

2024-01-31 20:04 UTC, cmsirbu requested changes
Left a bunch of minor fixes, great work otherwise! Once the build errors are fixed, we should be good to go.

Path has an extra `..` which causes build errors in all 3 includes in this file:

```
ERROR   -  Error reading page 'admin/install.md':
ERROR   -  No files found including '../../glossary.md' at admin/install.md:16
```

2024-01-31 20:04 UTC, cmsirbu commented on docs/admin/integrations/aristacv.md
> +- `nautobot-chatops` App was [installed with integration extra dependencies](./../install.md#installation-guide).
```suggestion
- `nautobot-chatops` App was [installed with integration extra dependencies](../install.md#installation-guide).
```

2024-01-31 20:04 UTC, cmsirbu commented on docs/admin/integrations/aristacv.md
> +- `nautobot-chatops` App is set up with at least one [enabled chat platform](./../install.md#chat-platforms-configuration) and [tested](./../install.md#test-your-chatbot).
```suggestion
- `nautobot-chatops` App is set up with at least one [enabled chat platform](../install.md#chat-platforms-configuration) and [tested](./../install.md#test-your-chatbot).
```

2024-01-31 20:04 UTC, cmsirbu commented on docs/admin/integrations/aristacv.md
> +Create a top-level command named `aristacv` in your enabled chat platform. For detailed instructions related to your specific chat platform, refer to the [platform specific set up](./../install.md#ch
```suggestion
Create a top-level command named `aristacv` in your enabled chat platform. For detailed instructions related to your specific chat platform, refer to the [platform specific set up](../install.md#chat-platforms-configuration).
```

2024-01-31 20:04 UTC, cmsirbu commented on docs/admin/integrations/grafana.md
> +- `nautobot-chatops` App was [installed with integration extra dependencies](./../install.md#installation-guide).
```suggestion
- `nautobot-chatops` App was [installed with integration extra dependencies](../install.md#installation-guide).
```

2024-01-31 20:04 UTC, cmsirbu commented on docs/admin/integrations/grafana.md
> +- `nautobot-chatops` App is set up with at least one [enabled chat platform](./../install.md#chat-platforms-configuration) and [tested](./../install.md#test-your-chatbot).
```suggestion
- `nautobot-chatops` App is set up with at least one [enabled chat platform](../install.md#chat-platforms-configuration) and [tested](./../install.md#test-your-chatbot).
```

2024-01-31 20:04 UTC, cmsirbu commented on docs/admin/integrations/grafana.md
> +Create a top-level command named `grafana` in your enabled chat platform. For detailed instructions related to your specific chat platform, refer to the [platform specific set up](./../install.md#cha
```suggestion
Create a top-level command named `grafana` in your enabled chat platform. For detailed instructions related to your specific chat platform, refer to the [platform specific set up](../install.md#chat-platforms-configuration).
```

2024-01-31 20:04 UTC, cmsirbu commented on docs/admin/integrations/ipfabric.md
> +- `nautobot-chatops` App was [installed with integration extra dependencies](./../install.md#installation-guide).
```suggestion
- `nautobot-chatops` App was [installed with integration extra dependencies](../install.md#installation-guide).
```

2024-01-31 20:04 UTC, cmsirbu commented on docs/admin/integrations/ipfabric.md
> +- `nautobot-chatops` App is set up with at least one [enabled chat platform](./../install.md#chat-platforms-configuration) and [tested](./../install.md#test-your-chatbot).
```suggestion
- `nautobot-chatops` App is set up with at least one [enabled chat platform](../install.md#chat-platforms-configuration) and [tested](./../install.md#test-your-chatbot).
```

2024-01-31 20:04 UTC, cmsirbu commented on docs/admin/integrations/ipfabric.md
> +Create a top-level command named `ipfabric` in your enabled chat platform. For detailed instructions related to your specific chat platform, refer to the [platform specific set up](./../install.md#ch
```suggestion
Create a top-level command named `ipfabric` in your enabled chat platform. For detailed instructions related to your specific chat platform, refer to the [platform specific set up](../install.md#chat-platforms-configuration).
```

2024-01-31 20:04 UTC, cmsirbu commented on docs/admin/integrations/meraki.md
> +- `nautobot-chatops` App was [installed with integration extra dependencies](./../install.md#installation-guide).
```suggestion
- `nautobot-chatops` App was [installed with integration extra dependencies](../install.md#installation-guide).
```

2024-01-31 20:04 UTC, cmsirbu commented on docs/admin/integrations/meraki.md
> +- `nautobot-chatops` App is set up with at least one [enabled chat platform](./../install.md#chat-platforms-configuration) and [tested](./../install.md#test-your-chatbot).
```suggestion
- `nautobot-chatops` App is set up with at least one [enabled chat platform](../install.md#chat-platforms-configuration) and [tested](./../install.md#test-your-chatbot).
```

2024-01-31 21:09 UTC, cmsirbu commented
```
--- a/docs/admin/install.md
+++ b/docs/admin/install.md
@@ -13,7 +13,7 @@ This guide outlines the process of enabling Nautobot ChatOps, which includes:
   - [Test Your Chatbot](#test-your-chatbot)
   - [Integrations Configuration](#integrations-configuration)

-{% include-markdown '../../glossary.md' heading-offset=1 %}
+{% include-markdown '../glossary.md' heading-offset=1 %}

 ## Prerequisites

@@ -126,7 +126,7 @@ Adjust the App's behavior with the following settings:
 ## Granting Access to the Chat Platform

 {%
-    include-markdown '../../models/accessgrant.md'
+    include-markdown '../models/accessgrant.md'
     start='<!--access-grant-->'
     heading-offset=1
 %}
@@ -134,7 +134,7 @@ Adjust the App's behavior with the following settings:
 ## Link Nautobot Account

 {%
-    include-markdown '../../models/chatopsaccountlink.md'
+    include-markdown '../models/chatopsaccountlink.md'
     start='<!--account-link-->'
     heading-offset=1
 %}
```

2024-02-01 07:41 UTC, snaselj commented
> ```
> --- a/docs/admin/install.md
> +++ b/docs/admin/install.md
> @@ -13,7 +13,7 @@ This guide outlines the process of enabling Nautobot ChatOps, which includes:
>    - [Test Your Chatbot](#test-your-chatbot)
>    - [Integrations Configuration](#integrations-configuration)
> 
> -{% include-markdown '../../glossary.md' heading-offset=1 %}
> +{% include-markdown '../glossary.md' heading-offset=1 %}
> 
>  ## Prerequisites
> 
> @@ -126,7 +126,7 @@ Adjust the App's behavior with the following settings:
>  ## Granting Access to the Chat Platform
> 
>  {%
> -    include-markdown '../../models/accessgrant.md'
> +    include-markdown '../models/accessgrant.md'
>      start='<!--access-grant-->'
>      heading-offset=1
>  %}
> @@ -134,7 +134,7 @@ Adjust the App's behavior with the following settings:
>  ## Link Nautobot Account
> 
>  {%
> -    include-markdown '../../models/chatopsaccountlink.md'
> +    include-markdown '../models/chatopsaccountlink.md'
>      start='<!--account-link-->'
>      heading-offset=1
>  %}
> ```

Fixed

2024-02-01 07:42 UTC, snaselj commented
This pull request has been refreshed and is ready for review.

2024-02-01 09:57 UTC, cmsirbu approved these changes

2024-02-05 17:52 UTC, smk4664 commented
I hope you don't mind, I fixed another mkdocs issue, unrelated to your pull request.

2024-02-05 17:52 UTC, smk4664 approved these changes

2024-02-05 17:53 UTC, merged